name: linux

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest
    services:
          postgres:
            image: postgres

            env:
              POSTGRES_PASSWORD: test
              POSTGRES_USER: postgres
              POSTGRES_DB: todo

            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Install diesel migrations cli
      run: cargo install diesel_cli --no-default-features --features postgres
    - name: do migrations
      run: diesel migration run
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
    - name: Build
      run: cargo build --verbose
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
