name: win 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: postgres
        password: test
        database: todo 
        port: 5432
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Install diesel migrations cli
      run: cargo install diesel_cli --no-default-features --features postgres
    - name: do migrations
      run: diesel migration run
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
    - name: Build
      run: cargo build --verbose
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
    - name: Run tyests
      run: cargo test --verbose
      env:
        DATABASE_URL: "postgres://postgres:test@localhost:5432/postgres"
